services:
  backend:
    image: sarab-backend:latest
    container_name: sarab_backend
    ports:
      - "5027:5027" 
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Sarab;User Id=sa;Password=!Sarab123;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    entrypoint: ["sh", "-c", "sleep 10 && dotnet Sarab-Platform.dll"]

  frontend:
    image: sarab-frontend:latest
    container_name: sarab_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - sqlserver
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Sarab_sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=!Sarab123
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: